version: "3.8"

services:
  nats1:
    container_name: nats1
    image: nats:latest
    entrypoint: /nats-server
    command: --server_name N1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats2:4245,nats://nats3:4245 -p 4222
    networks:
      - nats_demo
    ports:
      - 4222:4222
  nats2:
    container_name: nats2
    image: nats:latest
    entrypoint: /nats-server
    command: --server_name N2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats3:4245 -p 4222
    networks:
      - nats_demo
    ports:
      - 4223:4222
  nats3:
    container_name: nats3
    image: nats:latest
    entrypoint: /nats-server
    command: --server_name N3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245 -p 4222
    networks:
      - nats_demo
    ports:
      - 4224:4222

networks:
  nats_demo: 
    name: nats_demo


# https://hackernoon.com/nats-jetstream-a-new-way-to-create-resilient-message-queue