FROM docker.litellm.ai/berriai/litellm:v1.92.0

COPY  ./v1.92.0/responses/litellm_completion_transformation/transformation.py /app/.venv/lib/python3.13/site-packages/litellm/responses/litellm_completion_transformation/transformation.py