FROM docker.litellm.ai/berriai/litellm:main-stable
COPY ./v1.86.1/llms/anthropic/chat/transformation.py /app/.venv/lib64/python3.13/site-packages/litellm/llms/anthropic/chat/transformation.py
COPY ./v1.86.1/responses/litellm_completion_transformation/transformation.py /app/.venv/lib64/python3.13/site-packages/litellm/responses/litellm_completion_transformation/transformation.py