model_list:
  - model_name: deepseek-coder:1.3b
    litellm_params:
      model: ollama/deepseek-coder:1.3b
      api_base: http://host.docker.internal:11434
  - model_name: qwen2.5-coder:3b
    litellm_params:
      model: ollama/qwen2.5-coder:3b
      api_base: http://host.docker.internal:11434
  - model_name: qwen3:8b
    litellm_params:
      model: ollama/qwen3:8b
      api_base: http://host.docker.internal:11434
  - model_name: kimi-k2-thinking:cloud
    litellm_params:
      model: ollama/kimi-k2-thinking:cloud
      api_base: http://host.docker.internal:11434
  - model_name: minimax-m2.5:cloud
    litellm_params:
      model: ollama/minimax-m2.5:cloud
      api_base: http://host.docker.internal:11434

litellm_settings:
  # cache: true
  # cache_params: # set cache params for redis
  #   type: redis # type of cache to initialize (options: "local", "redis", "s3", "gcs")

  # callbacks: flatten_mcp.proxy_handler_instance
  drop_params: true
  # callbacks: ["my_custom_webhook"]
callback_settings:
  my_custom_webhook:
    callback_type: "generic_api"
    endpoint: "http://host.docker.internal:8888/webhook"
    headers:
      Content-Type: "application/json"
    event_types: ["llm_api_success", "llm_api_failed"]