apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  # labels:
  #   app.kubernetes.io/component: controller
  #   app.kubernetes.io/instance: ingress-nginx
  #   app.kubernetes.io/name: ingress-nginx
  #   app.kubernetes.io/part-of: ingress-nginx
  #   app.kubernetes.io/version: 1.13.1
  name: custom-nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: custom-nginx
  rules:
  - host: adminer.dev.internal
    http:
      paths:
      # - path: /adminer(/|$)(.*)
      - path: /
        # pathType: ImplementationSpecific
        pathType: Prefix
        backend:
          service:
            name: adminer
            port:
              number: 8080