events {
    worker_connections  1024;
}

http {
    # include /etc/nginx/fcgiwrap.conf;
    # include /app/map.json json;

    server {
        listen 80;

        location / {
            return 200 '{"message": "Hello from Nginx!"}';
        }

        # location /langfuse {
        #     proxy_set_header Host $host;
        #     proxy_pass http://langfuse-langfuse-web-1:3000;
        # }
        # location /langfuse/ {
        #     proxy_pass http://langfuse-langfuse-web-1:3000/langfuse/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
        location /my_langfuse {
            # rewrite ^/langfuse(/.*)$ $1 break;
            proxy_pass http://langfuse-langfuse-web-1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # location /my_langfuse/my_langfuse/ {
        #     # rewrite ^/my_langfuse(/.*)$ $1 break;
        #     # rewrite ^/my_langfuse/my_langfuse/(.*)$ /my_langfuse$2 break;
        #     # rewrite ^/my_langfuse/my_langfuse/(.*)$ /my_langfuse/$1 break;
        #     proxy_pass http://langfuse-langfuse-web-1:3000/my_langfuse/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
        # location ~ ^/my_langfuse/my_langfuse/(.*)$ {
        #     rewrite ^/my_langfuse/my_langfuse/(.*)$ /my_langfuse/$1 break;
        #     proxy_pass http://langfuse-langfuse-web-1:3000;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
        # location ~ ^/my_langfuse/my_langfuse/(.*)$ {
        #     rewrite ^/my_langfuse/my_langfuse/(.*)$ /my_langfuse/$1 redirect;
        # }
        location ~ ^/my_langfuse/my_langfuse/(.*)$ {
            # $server_port
            # $proxy_port
            # 8198
            return 301 http://$host:8198/my_langfuse/$1$is_args$args;
        }

    }
}