kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # --- OIDC 設定：讓 K8s 認識 GitLab ---
        oidc-issuer-url: "https://gitlab.com"
        oidc-client-id: "8804a714b9f0a8ba58d0f58d22179cae34ffa2b66a7dcf4660b0a4ffe7204299"
        oidc-username-claim: "email"
        # oidc-groups-claim: "groups"
    # kind: InitConfiguration
    # nodeRegistration:
    #   # 讓 Ingress Controller 知道要在哪個 node 執行
    #   node-labels: "ingress-ready=true"
  # 這裡最重要：將主機的 80/443 對應到節點容器內
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP