apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: stardard
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/poulin/github/python_practices/ai/ai_data/ollama/ollama"
    type: "DirectoryOrCreate"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: stardard