apiVersion: v1
kind: ConfigMap
metadata:
  name: vllm-router-config
  namespace: vllm
data:
  config.yaml: |
    host: "0.0.0.0"
    port: 8001
    # List of vLLM model server backends
    service_discovery: static
    static_backends:
      - url: "http://vllm-model-server-svc:8000"
    # Routing policy: round_robin | least_busy | session | random
    routing_logic: round_robin
    engine_stats_interval: 30
    request_stats_window: 60
