---
# Source: litellm-helm/templates/secret-dbcredentials.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-litellm-dbcredentials
data:
  # Password for the "postgres" user
  postgres-password: Tm9UYUdyRWFUcEFzU3dPckQ=
  username: bGl0ZWxsbQ==
  password: Tm9UYUdyRWFUcEFzU3dPckQ=
type: Opaque
