FROM nginx:alpine

# RUN rm -rf /usr/share/nginx/html/
# COPY index.html /usr/share/nginx/html/
# COPY default.conf /etc/nginx/conf.d/

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
COPY ./nginx.conf /etc/nginx/nginx.conf